# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [6]:
import numpy as np
structured_arry=np.array([('Jack',25,25),('Jill',22,55),('John',28,35)], dtype=[('Name','U10'),('Age','i4'),('Weight','i4')])
print(structured_arry)
add_data=np.array([('Jane',24,65)], dtype=[('Name','U10'),('Age','i4'),('Weight','i4')])
structured_arry=np.append(structured_arry, add_data)
print(structured_arry)
print(np.sort(structured_arry, order='Age'))


[('Jack', 25, 25) ('Jill', 22, 55) ('John', 28, 35)]
[('Jack', 25, 25) ('Jill', 22, 55) ('John', 28, 35) ('Jane', 24, 65)]
[('Jill', 22, 55) ('Jane', 24, 65) ('Jack', 25, 25) ('John', 28, 35)]


In [9]:
dtype=[("x","i4"),("y","i4")]
arr=np.array([(1,2),(3,4)], dtype=dtype)
print(arr)
eudic_dis=np.sqrt((arr["x"][1]-arr["x"][0])**2+(arr["y"][1]-arr["y"][0])**2)
print(eudic_dis)

[(1, 2) (3, 4)]
2.8284271247461903


[('Bob', 35, 80)]


In [ ]:

mat1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(mat1)
for i , j in np.ndindex(mat1.shape):
    if i==j:
        mat1[i][j]= 1
print(mat1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10  1 12]
 [13 14 15  1]]


In [24]:
mat=np.arange(1,37).reshape(6,6)
print(mat)
mat1=mat[1:4,2:5]
print(mat1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [31]:
mat=np.random.rand(5,5)
print(mat)
mat1=np.concatenate([mat[0,0:5], mat[1:5,0], mat[4,1:5], mat[1:4,4]]).reshape(4,4)
print(mat1)

[[0.03655381 0.46889436 0.55584255 0.4119657  0.249362  ]
 [0.81074926 0.49469914 0.42831203 0.20210141 0.89435809]
 [0.76889584 0.14448805 0.1721804  0.46030331 0.87225156]
 [0.45390983 0.72544985 0.40405806 0.95212363 0.50235104]
 [0.53114291 0.09572537 0.16853532 0.31041703 0.0615122 ]]
[[0.03655381 0.46889436 0.55584255 0.4119657 ]
 [0.249362   0.81074926 0.76889584 0.45390983]
 [0.53114291 0.09572537 0.16853532 0.31041703]
 [0.0615122  0.89435809 0.87225156 0.50235104]]


In [33]:
mat=np.random.randint(1,26, size=(5,5))
print(mat)
mean=np.mean(mat)
sd=np.std(mat)
var=np.var(mat)
median=np.median(mat)
print("Mean:", mean)
print("Standard Deviation:", sd)
print("Variance:", var)
print("Median:", median)

mat1=np.arange(1,10).reshape(3,3)
print(mat1)
mean1=np.mean(mat1)
sd1=np.std(mat1)
Normalized_mat=(mat1-mean1)/sd1
print(Normalized_mat)

[[ 9  6 25 23  6]
 [24  6 18 20 15]
 [ 9  1 15 15  2]
 [20  2 23  5 14]
 [17 20 10 11  6]]
Mean: 12.88
Standard Deviation: 7.366518852212353
Variance: 54.265600000000006
Median: 14.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [39]:
mat1=np.random.randint(1,100,size=(3,4))
mat2=np.random.randint(1,100,size=(3,4))
print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
added_mat=mat1+mat2
subtracted_mat=mat1-mat2
multiplied_mat=mat1*mat2
divided_mat=mat1/mat2
print("Added Matrix:\n", added_mat)
print("Subtracted Matrix:\n", subtracted_mat)
print("Multiplied Matrix:\n", multiplied_mat)
print("Divided Matrix:\n", divided_mat)

Matrix 1:
 [[51 30 43 58]
 [ 9 23 14 65]
 [47 36 50 89]]
Matrix 2:
 [[47 23 23 10]
 [84 22 27 63]
 [39  8 20 62]]
Added Matrix:
 [[ 98  53  66  68]
 [ 93  45  41 128]
 [ 86  44  70 151]]
Subtracted Matrix:
 [[  4   7  20  48]
 [-75   1 -13   2]
 [  8  28  30  27]]
Multiplied Matrix:
 [[2397  690  989  580]
 [ 756  506  378 4095]
 [1833  288 1000 5518]]
Divided Matrix:
 [[1.08510638 1.30434783 1.86956522 5.8       ]
 [0.10714286 1.04545455 0.51851852 1.03174603]
 [1.20512821 4.5        2.5        1.43548387]]


In [40]:
mat=np.arange(1,17).reshape(4,4)
print(mat)
row_wise_sum=np.sum(mat, axis=1)
col_wise_sum=np.sum(mat, axis=0)
print("Row-wise Sum:", row_wise_sum)
print("Column-wise Sum:", col_wise_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]


In [45]:
mat=np.random.randint(1,30,size=(3,3))
print(mat)
vac=np.random.randint(1,30,size=(3,))
print("Vector:", vac)
broadcasted_sum=mat+vac
print("Broadcasted Sum:\n", broadcasted_sum)
mat1=np.random.randint(1,31,size=(4,4))
print(mat1)
vac1=np.random.randint(1,31,size=(4,))
print("Vector:", vac1)
broadcasted_sum1=mat1-vac1
print("Broadcasted Sum1:\n", broadcasted_sum1)

[[ 7  8 15]
 [ 6 14  3]
 [26 12 15]]
Vector: [25 17  8]
Broadcasted Sum:
 [[32 25 23]
 [31 31 11]
 [51 29 23]]
[[23 27 20  1]
 [10  7 30 20]
 [14  9  9 19]
 [ 6 16 23  3]]
Vector: [21  9  1 22]
Broadcasted Sum1:
 [[  2  18  19 -21]
 [-11  -2  29  -2]
 [ -7   0   8  -3]
 [-15   7  22 -19]]


In [56]:
matr=-np.random.randint(1,50,size=(3,3))
print(matr)
det=np.linalg.det(matr).round(2)
print("Determinant:", det)
inv=np.linalg.inv(matr).round(2)
print("Inverse:\n", inv)
egv=np.linalg.eigvals(matr).round(2)
print("Eigenvalues: \n", egv)

[[-14 -36 -35]
 [-18  -3 -26]
 [-11 -26 -48]]
Determinant: 13031.0
Inverse:
 [[-0.04 -0.06  0.06]
 [-0.04  0.02  0.02]
 [ 0.03  0.   -0.05]]
Eigenvalues: 
 [-74.11  -9.47  18.58]


In [60]:
mat1=np.random.randint(1,15,size=(2,3))
print(mat1)
mat2=np.random.randint(1,15,size=(3,2))
print(mat2)
product=np.dot(mat1, mat2)
print("Product of Matrices:\n", product)
cross_product=np.cross(mat1, mat2.T)
print("Cross Product of Matrices:\n", cross_product)

[[14  9 13]
 [ 6  6 13]]
[[ 1  6]
 [13 10]
 [12  6]]
Product of Matrices:
 [[287 252]
 [240 174]]
Cross Product of Matrices:
 [[ -61 -155  173]
 [ -94   42   24]]


In [61]:
mat=np.arange(1,10).reshape(3,3)
print(mat)
mat=mat.reshape(1,9)
print(mat)
mat=mat.reshape(9,1)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [63]:
mat=np.random.randint(1,26,size=(5,5))
print(mat)
flattend_mat=mat.flatten()
print("Flattend Matrix:\n", flattend_mat)
reshaped_mat=flattend_mat.reshape(5,5)
print("Reshaped Matrix:\n", reshaped_mat)

mat2=np.random.randint(1,26,size=(5,5))
print(mat2)
mat2=mat2.reshape(25,)
print("Reshaped Matrix:\n", mat2)
mat2=mat2.reshape(5,5)
print("Original Matrix:\n", mat2)

[[ 9  3 10 21 11]
 [ 4  6 20 24 10]
 [22  7 12  5 16]
 [17 16  4 15  8]
 [ 8 20  2 22 20]]
Flattend Matrix:
 [ 9  3 10 21 11  4  6 20 24 10 22  7 12  5 16 17 16  4 15  8  8 20  2 22
 20]
Reshaped Matrix:
 [[ 9  3 10 21 11]
 [ 4  6 20 24 10]
 [22  7 12  5 16]
 [17 16  4 15  8]
 [ 8 20  2 22 20]]
[[14 14  1 17 11]
 [20 14 15 12 20]
 [ 9  9 11 17  9]
 [ 9 21 21 23 16]
 [21  5 20  4  6]]
Reshaped Matrix:
 [14 14  1 17 11 20 14 15 12 20  9  9 11 17  9  9 21 21 23 16 21  5 20  4
  6]
Original Matrix:
 [[14 14  1 17 11]
 [20 14 15 12 20]
 [ 9  9 11 17  9]
 [ 9 21 21 23 16]
 [21  5 20  4  6]]


In [64]:
mat=np.random.randint(1,40,size=(4,4))
print(mat)
mat[mat>10]=10  
print(mat)

[[23 28  5  3]
 [21 23 25 28]
 [ 5  6 30  7]
 [18 14 19  3]]
[[10 10  5  3]
 [10 10 10 10]
 [ 5  6 10  7]
 [10 10 10  3]]
